version: '3.3'
services:
  dozzle:
    container_name:  dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    ports:
            - 8300:8080
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        #- /volumes/mongodb/mongod.conf:/etc/mongod.conf
        #    command: [--auth]

