version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.8.0
    restart: unless-stopped
    ports:
      - 8305:9200/tcp
      - 8306:9300/tcp
    environment:
      discovery.type: single-node
    volumes:
      - /volumes/elasticsearch:/var/lib/elasticsearch
        #      - /volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
