version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27021:27017/tcp
    volumes:
      - /volumes/mongodb/data:/data/db
        #- /volumes/mongodb/mongod.conf:/etc/mongod.conf
        #    command: [--auth]

