#version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.2
    restart: unless-stopped
    ports:
      - 27021:27017
    volumes:
      - /volumes/mongodb/data:/data/db
    networks:
      - mongodb_network
networks:
  mongodb_network:
    driver: bridge
    name: mongodb_network



        
