version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - 27027:27017/tcp
    volumes:
      - /volumes/mongodb/data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        #    environment:
        #      MONGO_INITDB_DATABASE: admin
        #      MONGO_INITDB_ROOT_USERNAME: root
        #      MONGO_INITDB_ROOT_PASSWORD: roosh
    command: --auth
