version: '3.3'
services:
  mongotest:
    container_name: mongotest
    image: mongo
    restart: unless-stopped
    ports:
      - 27020:27017/tcp
    volumes:
      - /volumes/mongotest/data:/data/db
        #- /volumes/mongodb/mongod.conf:/etc/mongod.conf
        #    command: [--auth]

