version: '3.5'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - /volumes/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Miz@Blog
    ports:
            - '127.0.0.1:8308:3306'
  phpmyadmin:
    depends_on:
      - mysql
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8309:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Miz@Blog
      UPLOAD_LIMIT: 1G
      PMA_ARBITRAY: 1
networks:
    my-network-name:
        name: dockers_default

