version: '3.3'
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3 
    restart: unless-stopped
    ports:
            - 8317:8081
    volumes:
            - /volumes/nexus:/nexus-data
