version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
            - 80:80
            - 443:443
    volumes:
      - /volumes/html:/usr/share/nginx/html
      - /volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - /volumes/nginx/ssl:/etc/ssl

