version: '3.5'

services:
  nginx:
    container_name: nginx
    image: staticfloat/nginx-certbot 
    restart: unless-stopped
    ports:
            - 80:80
            - 443:443
    volumes:
      - /volumes/html:/usr/share/nginx/html
      - /volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - /volumes/nginx/letsencrypt:/etc/letsencrypt
    environment:
      - CERTBOT_EMAIL= 'ehsan.shirzadi@gmail.com'

