version: '3.3'
services:
  owncloud:
    container_name: owncloud
    image: owncloud:latest
    restart: unless-stopped
    ports:
            - 8313:80
    volumes:
      - /volumes/owncloud:/var/www/html
