version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: rojandweb_mysql
    volumes:
      - /home/debian/volumes/rojand/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Rojand
      MYSQL_DATABASE: rojand
      MYSQL_USER: rojand
      MYSQL_PASSWORD: rojand
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    container_name: rojandweb_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Miz@Blog? 
      UPLOAD_LIMIT: 1G
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    container_name: rojandweb_wp
    image: wordpress:latest
    ports:
      - '8001:80'
    restart: always
    volumes: ['/home/debian/volumes/rojand/wp:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mizblog
      WORDPRESS_DB_PASSWORD: Miz@Blog
      WORDPRESS_DB_NAME : mizblog
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
