version: '3.1'

services:

  wordpress:
    container_name: wp_ariana
    image: wordpress
    restart: always
    ports:
      - 8889:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /home/debian/web/ariana-web/wp:/var/www/html

  db:
    container_name: db_ariana
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /home/debian/web/ariana-web/db:/var/lib/mysql

