services:
  sentry:
    image: sentry:latest
    depends_on:
      - postgres
      - redis
      - kafka
      - zookeeper
    environment:
      SENTRY_SECRET_KEY: '<your-secret-key>'
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_KAFKA_HOST: kafka
    ports:
      - "9000:9000"
    volumes:
      - sentry-data:/var/lib/sentry/files
      - sentry-config:/etc/sentry
    command: ["sentry", "run", "web"]

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: sentry
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - sentry-redis:/data

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - sentry-kafka:/kafka

  cron:
    image: sentry:latest
    depends_on:
      - postgres
      - redis
      - kafka
    command: ["sentry", "run", "cron"]
    volumes:
      - sentry-config:/etc/sentry

  worker:
    image: sentry:latest
    depends_on:
      - postgres
      - redis
      - kafka
    command: ["sentry", "run", "worker"]
    volumes:
      - sentry-config:/etc/sentry

volumes:
  sentry-data:
  sentry-config:
  sentry-postgres:
  sentry-redis:
  sentry-kafka:  
