version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Miz@Blog?
      MYSQL_DATABASE: mizblog
      MYSQL_USER: mizblog
      MYSQL_PASSWORD: Miz@Blog
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Miz@Blog? 
      UPLOAD_LIMIT: 1G
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8888:80'
    restart: always
    volumes: ['/home/debian/volumes/mizblog/wp:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mizblog
      WORDPRESS_DB_PASSWORD: Miz@Blog
      WORDPRESS_DB_NAME : mizblog
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
