#https://github.com/sissbruecker/linkding
version: '3'

services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    ports:
      - 8001:9090
    volumes:
      - /volumes/linkding/data:/etc/linkding/data
        #    env_file:
        #      - .env
    restart: unless-stopped
