#https://github.com/louislam/uptime-kuma
version: '3'
services:
  uptime:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    ports:
      - 8002:3001 
    volumes:
      - /volumes/uptimekuma:/app/data
