version: '3.5'

services:
  nginx:
    container_name: ng
    build: .
    restart: unless-stopped
    ports:
            - 80:80
            - 443:443
    volumes:
      - /home/debian/volumes/html:/usr/share/nginx/html
      #- /home/debian/volumes/nginx/conf.d:/etc/nginx/user.conf.d:ro
      - /home/debian/volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - /home/debian/volumes/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - external
networks:
  external:
    name:  projects

